### ISSUE TITLE
[Travel] The city search suggestions aren't matching the language I type

### ISSUE THREAD

**Issue by tinahsieh** [mozilla-tw/FirefoxLite#4424]
**Describe the bug**
When I search for "Bali“, the suggestions show "峇里島“ instead of "Bali" (my device language is set as [zh]). 

**Todos**
- [x] Tina check with Booking.com to see if the API support multi-language
- [x] Tina define if the behavior needs to be modified based on Booking.com's reply
- [x] (optional) Benjamin makes sure the changes can be implemented

**Comment by weslyhuang** [comment]
need to clarify and list down the expected behavior/design.

**Comment by tinahsieh** [comment]
Booking.com's reply: "Users can only choose one language at a time."
Booking.com also suggest FxLite to provide a setting for users to set languages.  

Since the API doesn't support multi-languages, we'll keep the design as current one. I'll close this issue.
